### ISSUE TITLE
Tensorflow support

### ISSUE THREAD

**Issue by tiagofrepereira2012** [usnistgov/trojai-example#1]
Hi,

I've downloaded your dataset from here (https://pages.nist.gov/trojai/docs/data.html) and I'm wondering if it's possible to have the same models (tampered/not tampered) in tensorflow format.

Thanks

Tiago

**Comment by mmajurski** [comment]
The TrojAI codebase is written in PyTorch. While it would be great to disseminate both, we just don't have the time to build models in both Tensorflow and Pytorch. 

Thank you,
Michael
