### ISSUE TITLE
Feature Extraction Issue

### ISSUE THREAD

**Issue by SolidShen** [usnistgov/trojai-example#10]
Hi,
I found this line of code lies in the inner for loop, which means it will times 'model_skew["__all__"]' each time when a new feature added. Therefore, the first feature stored in the list will be processed multiple times.  Is it by design or a bug? 
https://github.com/usnistgov/trojai-example/blob/60fcf6e0979520fb62005f590a878789ef278a18/detector.py#L181

Best,
Guangyu

**Comment by pdessauw** [comment]
Hi Guangyu, 

It is indeed a bug, that has just been fixed.

Thank you for pointing it out!
Have a nice day!
